#!/usr/bin/env awk

{
    gsub("#/components/schemas/AgeRatingDeclarationWithoutIncludesResponse", "#/components/schemas/AgeRatingDeclarationResponse")
    gsub("#/components/schemas/AppCategoriesWithoutIncludesResponse", "#/components/schemas/AppCategoriesResponse")
    gsub("#/components/schemas/AppCategoryWithoutIncludesResponse", "#/components/schemas/AppCategoryResponse")
    gsub("#/components/schemas/AppEncryptionDeclarationWithoutIncludesResponse", "#/components/schemas/AppEncryptionDeclarationResponse")
    gsub("#/components/schemas/AppPreOrderWithoutIncludesResponse", "#/components/schemas/AppPreOrderResponse")
    gsub("#/components/schemas/AppStoreVersionPhasedReleaseWithoutIncludesResponse", "#/components/schemas/AppStoreVersionPhasedReleaseResponse")
    gsub("#/components/schemas/AppsWithoutIncludesResponse", "#/components/schemas/AppsResponse")
    gsub("#/components/schemas/AppWithoutIncludesResponse", "#/components/schemas/AppResponse")
    gsub("#/components/schemas/BetaAppLocalizationsWithoutIncludesResponse", "#/components/schemas/BetaAppLocalizationsResponse")
    gsub("#/components/schemas/BetaAppReviewDetailWithoutIncludesResponse", "#/components/schemas/BetaAppReviewDetailResponse")
    gsub("#/components/schemas/BetaAppReviewSubmissionWithoutIncludesResponse", "#/components/schemas/BetaAppReviewSubmissionResponse")
    gsub("#/components/schemas/BetaBuildLocalizationsWithoutIncludesResponse", "#/components/schemas/BetaBuildLocalizationsResponse")
    gsub("#/components/schemas/BetaGroupsWithoutIncludesResponse", "#/components/schemas/BetaGroupsResponse")
    gsub("#/components/schemas/BetaLicenseAgreementWithoutIncludesResponse", "#/components/schemas/BetaLicenseAgreementResponse")
    gsub("#/components/schemas/BetaTestersWithoutIncludesResponse", "#/components/schemas/BetaTestersResponse")
    gsub("#/components/schemas/BuildIconsWithoutIncludesResponse", "#/components/schemas/BuildIconsResponse")
    gsub("#/components/schemas/BuildsWithoutIncludesResponse", "#/components/schemas/BuildsResponse")
    gsub("#/components/schemas/BuildWithoutIncludesResponse", "#/components/schemas/BuildResponse")
    gsub("#/components/schemas/BundleIdCapabilitiesWithoutIncludesResponse", "#/components/schemas/BundleIdCapabilitiesResponse")
    gsub("#/components/schemas/BundleIdWithoutIncludesResponse", "#/components/schemas/BundleIdResponse")
    gsub("#/components/schemas/CertificatesWithoutIncludesResponse", "#/components/schemas/CertificatesResponse")
    gsub("#/components/schemas/DevicesWithoutIncludesResponse", "#/components/schemas/DevicesResponse")
    gsub("#/components/schemas/EndUserLicenseAgreementWithoutIncludesResponse", "#/components/schemas/EndUserLicenseAgreementResponse")
    gsub("#/components/schemas/PreReleaseVersionsWithoutIncludesResponse", "#/components/schemas/PreReleaseVersionsResponse")
    gsub("#/components/schemas/PrereleaseVersionWithoutIncludesResponse", "#/components/schemas/PrereleaseVersionResponse")
    gsub("#/components/schemas/ProfilesWithoutIncludesResponse", "#/components/schemas/ProfilesResponse")
    gsub("#/components/schemas/RoutingAppCoverageWithoutIncludesResponse", "#/components/schemas/RoutingAppCoverageResponse")
    gsub("#/components/schemas/TerritoriesWithoutIncludesResponse", "#/components/schemas/TerritoriesResponse")
    print
}
