name: Bazel

on:
  push:
    branches:
      - main
    paths:
      - '.bazelrc'
      - '.bazelversion'
      - '.github/workflows/bazel.yml'
      - '**/BUILD.bazel'
      - '**/BUILD.overlay'
      - 'bazel/*'
      - 'Examples/**/*.swift'
      - 'MODULE.bazel'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
  pull_request:
    paths:
      - '.bazelrc'
      - '.bazelversion'
      - '.github/workflows/bazel.yml'
      - '**/BUILD.bazel'
      - '**/BUILD.overlay'
      - 'bazel/*'
      - 'Examples/**/*.swift'
      - 'MODULE.bazel'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
  workflow_dispatch: ~

concurrency:
  group: bazel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    runs-on: macos-15
    steps:
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
      - uses: actions/checkout@v4
      - run: bazel test //...
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['6.1']
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          bazelisk-version: 1.x
      - uses: actions/checkout@v4
      - run: bazel test //...
  bzlmod-e2e-macOS:
    runs-on: macos-15
    steps:
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
      - uses: actions/checkout@v4
      - run: bazel build //...
        working-directory: Examples/bzlmod
  bzlmod-e2e-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['6.1']
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          bazelisk-version: 1.x
      - uses: actions/checkout@v4
      - run: bazel build //...
        working-directory: Examples/bzlmod
