name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: ~

jobs:
  library-apple:
    runs-on: macos-14
    strategy:
      matrix:
        xcode:
          - '15.4'
        appleos:
          - ios
          - macos
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test-library-xcode-${{ matrix.appleos }}

  library-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    steps:
      - uses: actions/checkout@v4
      - name: Install make
        run: apt update && apt install make -y
      - name: Run tests
        run: make test-library

  examples-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.10
    steps:
      - uses: actions/checkout@v4
      - name: Install make
        run: apt update && apt install make -y
      - name: Run tests
        run: make build-examples
