name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The new version to tag, ex: 1.0.5'
        required: true
        type: string
      prerelease:
        default: true
        description: Indicator of whether or not this is a prerelease.
        type: boolean

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
      - uses: actions/checkout@v4
      - run: bazel test //...
      - name: Smoke test
        run: bazel test //...
        working-directory: ./Examples/bzlmod
      - name: Prepare release
        run: |-
          PREFIX="asc_swift-${{ inputs.tag }}"
          ARCHIVE="asc_swift-${{ inputs.tag }}.tar.gz"
          git archive --format=tar --prefix="${PREFIX}/" "${{ inputs.tag }}" | gzip > $ARCHIVE
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "asc_swift-*.tar.gz"
          fail_on_unmatched_files: true
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: true
