name: xcodebuild

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/xcodebuild.yml'
      - 'Examples/**/*.swift'
      - 'Package*'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/xcodebuild.yml'
      - 'Examples/**/*.swift'
      - 'Package*'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
  workflow_dispatch: ~

concurrency:
  group: xcodebuild-${{ github.ref }}
  cancel-in-progress: true

jobs:
  xcodebuild:
    runs-on: macos-15
    strategy:
      matrix:
        xcode: ['16.4']
        destination:
          - 'platform=macOS'
          - 'platform=iOS Simulator,name=iPhone 16 Pro Max'
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - run: xcodebuild -version
      - name: Build with Xcode
        run: |-
          set -o pipefail

          xcodebuild test \
            -scheme AppStoreConnect-Package \
            -destination "${{ matrix.destination }}" \
          | xcbeautify --renderer github-actions
